site: Ben Warren

url:
baseurl:

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      featured_image: /images/social_new.jpg
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      featured_image: /images/social_new.jpg
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      featured_image: /images/social_new.jpg
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      featured_image: /images/social_new.jpg
  -
    scope:
      path: ""
      type: "home"
    values:
      layout: "home"
      featured_image: /images/social_new.jpg

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sass:
  style: compressed

plugins:
  - jekyll-sitemap

paginate: 7
paginate_path: "/blog/page-:num/"
